#!/bin/sh

set -ex


#
# I would have used a Makefile, but the AWS CLI docker image does not come with
# `make`, which defeats the purpose of incoveniencing ourselves with `make` 
# instead of just plain old bash scripts
# 

function test() {
    cd ./function

    PYTHON_VERSION=$(cat .python-version)
    python --version | grep $PYTHON_VERSION > /dev/null || echo "Python $PYTHON_VERSION not found"

    python test_function.py

    cd ..    
}

function deploy() {

    # Enforce version
    cd ./deploy
    TERRAFORM_VERSION=$(cat .terraform-version)
    terraform --version | grep $TERRAFORM_VERSION > /dev/null || echo "Python $TERRAFORM_VERSION not found"
    cd ..

    cd ./deploy

    # Initialise terraform
    # Vars come from .env which is sourced before the function is called
    terraform init \
        -backend-config="access_key=$AWS_ACCESS_KEY_ID" \
        -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY" \
        -backend-config="region=$AWS_REGION" \
        -backend-config="bucket=$S3_BUCKET" \
        -backend-config="dynamodb_table=$DYNAMODB_TABLE" \
        -backend-config="key=$STATE_KEY" 

    # Set workspace to the current branch
    export TF_VAR_branch=$(git rev-parse --abbrev-ref HEAD)
    terraform workspace new $TF_VAR_branch || terraform workspace select $TF_VAR_branch

    # Deploy the function
    AUTO_APPROVE=''
    if [ -n "$CIRCLECI" ]; then
        AUTO_APPROVE='-auto-approve'
    fi

    terraform apply $AUTO_APPROVE

    cd ..
}

# If first argument is not set, print help and exit
if [ -z "$1" ]; then
    echo "Usage: $0 [test|deploy]"
    exit 1
fi

# If just initial, replace with full command
if [ "$1" == "t" ]; then
    set -- "test"
elif [ "$1" == "d" ]; then
    set -- "deploy"
fi

# Source the .env file if it exists
if [ -f .env ]; then
    source .env
fi

"$1"